spring:
  application:
    name: spring-ai-1
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-5.6-luna
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/memory_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver